### ISSUE TITLE
Error when opening bal files with Atom on OSX

### ISSUE THREAD

**Issue by kasunbg** [ballerinalang/plugin-atom#8]
**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [language-ballerina](https://github.com/wso2/plugin-atom) package 0.8.0

### Stack Trace

Failed to activate the language-ballerina package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kasun/delete/plugin-atom-0.8.0-RC1/lib/BallerinaClassLoader.js:11:15)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kasun/delete/plugin-atom-0.8.0-RC1/lib/language-ballerina.js:2:43)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:922:28
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.triggerActivationHook (/app.asar/src/package-manager.js:594:43)
    at Workspace.module.exports.Workspace.handleGrammarUsed (/app.asar/src/workspace.js:618:34)
    at TextEditor.module.exports.TextEditor.observeGrammar (/app.asar/src/text-editor.js:595:7)
    at /app.asar/src/workspace.js:261:189
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/app.asar/src/pane-container.js:390:27)
    at /app.asar/src/pane-container.js:374:28
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.addItem (/app.asar/src/pane.js:506:20)
    at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:449:14)
    at /app.asar/src/workspace.js:545:18
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Commands

```
  3x -0:12.7.0 core:close (input.hidden-input)
     -0:07.1.0 application:open (atom-pane.pane.active)
```

### Non-Core Packages

```
autocomplete-java 1.2.5 
java-generator 2.2.3 
language-ballerina 0.8.0 
lodash-modules-snippets 0.2.1 
markdown-preview-plus 2.4.3 
markdown-writer 2.6.4 
```

**Comment by dakshika** [comment]
We'll check, Thanks for reporting

**Comment by ramindu90** [comment]
@kasunbg : since we are installing the plugin using the zip, we have to download the dependencies manually. After downloading the package, you will have to navigate to the plugin folder and execute "apm install"

**Comment by dakshika** [comment]
@kasunbg : Can you verify this?

**Comment by kasunbg** [comment]
Yes, followed the instructions in readme.md and it works.
